### ISSUE TITLE
machine:init doesn't work with capistrano 3.4

### ISSUE THREAD

**Issue by aLamprecht** [hanseventures/deploy-mate#12]
Wenn man den Task ausführt, bekommt man folgende Fehlermeldung:
```
NoMethodError: undefined method `verbosity' for "/usr/bin/env machine:install:htop\n":String
/Users/anne/.rvm/gems/ruby-2.2.0@recruiting/gems/sshkit-1.3.0/lib/sshkit/formatters/pretty.rb:10:in `write'
/Users/anne/.rvm/gems/ruby-2.2.0@recruiting/gems/sshkit-1.3.0/lib/sshkit/backends/printer.rb:14:in `block in execute'
/Users/anne/.rvm/gems/ruby-2.2.0@recruiting/gems/sshkit-1.3.0/lib/sshkit/backends/printer.rb:13:in `tap'
/Users/anne/.rvm/gems/ruby-2.2.0@recruiting/gems/sshkit-1.3.0/lib/sshkit/backends/printer.rb:13:in `execute'
/Users/anne/.rvm/gems/ruby-2.2.0@recruiting/gems/deploy_mate-0.15/lib/capistrano/tasks/machine.rake:9:in `block (3 levels) in <top (required)>'
/Users/anne/.rvm/gems/ruby-2.2.0@recruiting/gems/sshkit-1.3.0/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/Users/anne/.rvm/gems/ruby-2.2.0@recruiting/gems/sshkit-1.3.0/lib/sshkit/backends/netssh.rb:54:in `run'
/Users/anne/.rvm/gems/ruby-2.2.0@recruiting/gems/sshkit-1.3.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => machine:init
```

Es scheint so, dass die Methodenaufrufe wie ```invoke "machine:install:htop"``` in der tasks/machine.rake keine Strings sein sollten (pure Vermutung).
